---
name: Lint Code Base
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, dev ]

  workflow_dispatch:

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v3.17.1
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: /
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_CSS: true

      - name: Use Node.js 14.17
        uses: actions/setup-node@v2
        with:
          node-version: 14.17
      - name: npm ci
        run: npm ci
      - name: test
        run: npm test
      - name: build
        run: npm run build --if-present
